version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - hausmesse-2022-network
    ports:
      - 3306:3306

  adminer:
    image: adminer
    depends_on:
      - db
    networks:
      - hausmesse-2022-network
    restart: always
    ports:
      - 8080:8080

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - db
    networks:
      - hausmesse-2022-network
    restart: always
    privileged: true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - server
      - frontend
    networks:
      - hausmesse-2022-network
    restart: always
    ports:
      - 80:80

  server:
    env_file:
      - ./.env
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    depends_on:
      - db
    networks:
      - hausmesse-2022-network
    restart: always
    ports:
      - 5001:${SERVER_PORT}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - server
    networks:
      - hausmesse-2022-network
    restart: always
    ports:
      - 3001:${FRONTEND_PORT}

networks:
  hausmesse-2022-network:
